In [2]:
import numpy as np

### Q2
#### Part (e)

##### Code for (a)

In [13]:
X = np.array([[2,1,1],
             [2,2,0],
             [0.5,0.5,1],
             [0,1,3],
             [0,0,3]])
X

array([[2. , 1. , 1. ],
       [2. , 2. , 0. ],
       [0.5, 0.5, 1. ],
       [0. , 1. , 3. ],
       [0. , 0. , 3. ]])

##### Code for (b)

In [16]:
c = np.array([1,0.2,0.5,0.1,0.4]).reshape(-1,1)
c

array([[1. ],
       [0.2],
       [0.5],
       [0.1],
       [0.4]])

In [17]:
X.T @ c

array([[2.65],
       [1.75],
       [3.  ]])

##### Code for (c)

In [18]:
p = np.array([1,1,0]).reshape(-1,1)
p

array([[1],
       [1],
       [0]])

In [19]:
X @ p

array([[3.],
       [4.],
       [1.],
       [1.],
       [0.]])

##### Code for (d)

In [20]:
p = np.array([3,3,3]).reshape(-1,1)
p

array([[3],
       [3],
       [3]])

In [21]:
(X @ p).T @ c

array([[22.2]])

### Q3
#### Part (g)

In [23]:
X = np.array([[4,1,1],
             [-3,2,2],
             [1,-3,2],
             [5,1,3]])
X

array([[ 4,  1,  1],
       [-3,  2,  2],
       [ 1, -3,  2],
       [ 5,  1,  3]])

##### Code for (a)

In [24]:
y = np.array([9,7,1,16]).reshape(-1,1)
y

array([[ 9],
       [ 7],
       [ 1],
       [16]])

In [25]:
w = np.array([1,2,3]).reshape(-1,1)
w

array([[1],
       [2],
       [3]])

In [26]:
y_hat = X @ w
y_hat

array([[ 9],
       [ 7],
       [ 1],
       [16]])

In [27]:
y_hat == y

array([[ True],
       [ True],
       [ True],
       [ True]])

##### Code for (b)

In [33]:
for i in range(1,5):
    w = np.array([np.where(i == 1,1,0),
              np.where(i == 2,1,0),
              np.where(i == 3,1,0),
              np.where(i == 4,1,0)]).reshape(-1,1)
    print(w.T @ X)

[[4 1 1]]
[[-3  2  2]]
[[ 1 -3  2]]
[[5 1 3]]


##### Code for (c)

In [34]:
a = 2.4
b = 3.3
for i in range(1,5):
    for j in range(1,5):
        w = np.array([a * np.where(i == 1,1,0) + b * np.where(j == 1,1,0),
                      a * np.where(i == 2,1,0) + b * np.where(j == 2,1,0),
                      a * np.where(i == 3,1,0) + b * np.where(j == 3,1,0),
                      a * np.where(i == 4,1,0) + b * np.where(j == 4,1,0)]
                    ).reshape(-1,1)
        print(w.T @ X)

[[22.8  5.7  5.7]]
[[-0.3  9.   9. ]]
[[12.9 -7.5  9. ]]
[[26.1  5.7 12.3]]
[[6.  8.1 8.1]]
[[-17.1  11.4  11.4]]
[[-3.9 -5.1 11.4]]
[[ 9.3  8.1 14.7]]
[[15.6 -3.9  8.1]]
[[-7.5 -0.6 11.4]]
[[  5.7 -17.1  11.4]]
[[18.9 -3.9 14.7]]
[[25.2  5.7 10.5]]
[[ 2.1  9.  13.8]]
[[15.3 -7.5 13.8]]
[[28.5  5.7 17.1]]


##### Code for (d)

In [35]:
for i in range(1,4):
    w = np.array([np.where(i == 1,1,0),
              np.where(i == 2,1,0),
              np.where(i == 3,1,0)]).reshape(-1,1)
    print(X @ w)

[[ 4]
 [-3]
 [ 1]
 [ 5]]
[[ 1]
 [ 2]
 [-3]
 [ 1]]
[[1]
 [2]
 [2]
 [3]]


##### Code for (e)

In [36]:
w = np.array([-1,10,0]).reshape(-1,1)
w

array([[-1],
       [10],
       [ 0]])

In [37]:
X @ w

array([[  6],
       [ 23],
       [-31],
       [  5]])

### Q6
#### Part (c)

In [38]:
import scipy.io as sio
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

In [ ]:
# n = number of poitns
# z = points where polynomial is evaluated
# p = array to store the values of the interpolated polynomials

n = 100
z_1 = np.linspace(-1, 1, n)
z_2 = np.linspace(-1, 1, n)

w_size = ##TODO
w = np.random.rand(w_size)
X = np.zeros((n,w_size))

