# <font color='maroon'>Mathematical Foundations of Machine Learning, University of Chicago, Fall 2023</font>

## **Lecture 2**

## first load necessary packages



In [3]:
import numpy as np
from IPython.display import display, Math, HTML
import pandas as pd

## now create a vector and then print it

In [4]:
x = np.array([1,2,3])

print("x =",x)
xT = np.transpose(x)
xT2 = x.transpose()
xT3 = x.T
print("x.T=",x.T)
display(Math(rf'x = {x},\; x^\top = {xT}={xT2}={xT3}'))
print("x.shape = %s,\nxT.shape = %s,\nxT2.shape = %s,\nxT3.shape = %s" %(x.shape,xT.shape,xT2.shape,xT3.shape))


x = [1 2 3]
x.T= [1 2 3]


<IPython.core.display.Math object>

x.shape = (3,),
xT.shape = (3,),
xT2.shape = (3,),
xT3.shape = (3,)


### (note that arrays are not lists)

In [5]:
w = [1,2,3]

print("x/4 = ",x/4)
print("w/4 = ",w/4)  # this results in an error

x/4 =  [0.25 0.5  0.75]


TypeError: ignored

## compute an inner (dot) product


In [7]:
x = np.array([1,2,3])
w = np.array([4,5,6])
p = np.dot(x,w)
p2 = x*w
p3 = x@w

print("x^T w = ", p , "\n")
print("np.dot(x,w) = %s, x*w = %s, x@w = %s" % (p,p2,p3), '\n')
display(Math(rf'x^\top w = ({x[0]}\times {w[0]}) + ({x[1]}\times {w[1]}) + ({x[2]}\times {w[2]}) = {p}'))

print("x w^T = ",np.outer(x,w))

x^T w =  32 

np.dot(x,w) = 32, x*w = [ 4 10 18], x@w = 32 



<IPython.core.display.Math object>

x w^T =  [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## matrices

Defining a matrix and printing it several different ways

In [8]:
X = np.array([[1, 1, 0, 0, 0],[0, 1, 2, 0, 3],[0, 5, 0, 6, 0]])

print("X =",X)
print("X = ",pd.DataFrame(X))
print("X =\n",pd.DataFrame(X))
print("X = ",pd.DataFrame(X).to_string(index=False,header=False))

print("X = ")
HTML(pd.DataFrame(X).to_html(index=False,header=False))


X = [[1 1 0 0 0]
 [0 1 2 0 3]
 [0 5 0 6 0]]
X =     0  1  2  3  4
0  1  1  0  0  0
1  0  1  2  0  3
2  0  5  0  6  0
X =
    0  1  2  3  4
0  1  1  0  0  0
1  0  1  2  0  3
2  0  5  0  6  0
X =  1 1 0 0 0
0 1 2 0 3
0 5 0 6 0
X = 


## matrix-vector products

In [9]:
X = np.array([[1, 1, 0, 0, 0],[0, 1, 2, 0, 3],[0, 5, 0, 6, 0]])
y = np.array([1,2,3])
w = np.array([2,4,6,8,10])


print("y@X = %s" % (y@X))
display(Math(rf'y^\top X = '),y@X)

print("\nX@w = %s" % (X@w))
display(Math(rf'Xw = '),X@w)

print("\ny@X@w = %s" % (y@X@w))
display(Math(rf'y^\top Xw = '),y@X@w)



y@X = [ 1 18  4 18  6]


<IPython.core.display.Math object>

array([ 1, 18,  4, 18,  6])


X@w = [ 6 46 68]


<IPython.core.display.Math object>

array([ 6, 46, 68])


y@X@w = 302


<IPython.core.display.Math object>

302

In [11]:
print("X = ",X)
print("1st row of X = [1, 0, 0]@X = ",np.array([1, 0, 0])@X )
print("2nd row of X = [0, 1, 0]@X = ",np.array([0, 1, 0])@X )
print("3rd row of X = [0, 0, 1]@X = ",np.array([0, 0, 1])@X )
print("2x 1st row + 3rd row of X = [2, 0, 1]@X = ",np.array([2, 0, 1])@X)

X =  [[1 1 0 0 0]
 [0 1 2 0 3]
 [0 5 0 6 0]]
1st row of X = [1, 0, 0]@X =  [1 1 0 0 0]
2nd row of X = [0, 1, 0]@X =  [0 1 2 0 3]
3rd row of X = [0, 0, 1]@X =  [0 5 0 6 0]
2x 1st row + 3rd row of X = [2, 0, 1]@X =  [2 7 0 6 0]


In [12]:
print("X = \n",X)
print("1st col of X = X@[1,0,0,0,0] = ",X@np.array([1,0,0,0,0]) )
print("2nd col of X = X@[0,1,0,0,0] = ",X@np.array([0,1,0,0,0]) )
print("3rd col of X = X@[0,0,1,0,0] = ",X@np.array([0,0,1,0,0]) )
print("4th col of X = X@[0,0,0,1,0] = ",X@np.array([0,0,0,1,0]) )
print("5th col of X = X@[0,0,0,0,1] = ",X@np.array([0,0,0,0,1]) )

print("2x 1st col + 4th col = X@[2,0,0,1,0] = ",X@np.array([2,0,0,1,0]))

X = 
 [[1 1 0 0 0]
 [0 1 2 0 3]
 [0 5 0 6 0]]
1st col of X = X@[1,0,0,0,0] =  [1 0 0]
2nd col of X = X@[0,1,0,0,0] =  [1 1 5]
3rd col of X = X@[0,0,1,0,0] =  [0 2 0]
4th col of X = X@[0,0,0,1,0] =  [0 0 6]
5th col of X = X@[0,0,0,0,1] =  [0 3 0]
2x 1st col + 4th col = X@[2,0,0,1,0] =  [2 0 6]
